## GitHub profile

coffee:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "md:coffee"
      schema: prod
      threads: 8
    test:
      type: duckdb
      path: "md:coffee"
      schema: test
      threads: 8
