 select coffee_id,
        rating_id,
        coffee_name,
        roaster_id,
        roaster,
        origin_id,
        country,
        world_region,
        country_region,
        is_available,
        availability,
        is_decaf,
        caffeine_content,
        roast_darkness,
        varietals,
        process,
        elevation_min,
        elevation_max,
        elevation,
        coffees.flavor_profile_key,
        is_favorite,
        brew_method,
        rating,
        is_liked,
        rating_value,
        rated_date,
        added_at,
        is_current
        
   from {{ ref('coffees') }}
   join {{ ref('ratings') }}
  using (coffee_id)
