name: CI job

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_dbt:
    name: Build dbt in test environment
    runs-on: ubuntu-latest

    environment: test

    env:
      DBT_PROFILES_DIR: ".github"
      motherduck_token: ${{ secrets.motherduck_token }}

    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          pip install "duckdb==${{ vars.duckdb_version }}"
          pip install dbt-core==${{ vars.dbt_core_version }} dbt-duckdb
          dbt deps
      # dbt related commands here - run use --target prod/dev to run for specific environments
      - name: Build dbt models
        run: dbt build --target test

  deploy_evidence:
    name: Preview Evidence on DigitalOcean
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Deploy the app
      uses: digitalocean/app_action/deploy@v2
      with:
        app_name: lunsford-coffee
        deploy_pr_preview: "true"
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

