name: Deploy dbt and Docs

on:
  schedule:
    - cron: "30 3 * * *"
  push:
    branches:
      # run on push to main branch
      - main
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  deploy_dbt:
    name: Deploy dbt to prod
    runs-on: ubuntu-latest

    environment: prod

    env:
      DBT_PROFILES_DIR: ".github"
      motherduck_token: ${{ secrets.motherduck_token }}

    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          pip install "duckdb==${{ vars.duckdb_version }}"
          pip install dbt-core==${{ vars.dbt_core_version }} dbt-duckdb
          dbt deps
      # dbt related commands here - run use --target prod/dev to run for specific environments
      - name: Build dbt models
        run: dbt build --target prod

      - name: Generate docs
        run: dbt docs generate

      # Configure Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "target/"

  deploy_evidence:
    name: Deploy Evidence
    # Add a dependency to the build job
    needs: deploy_dbt

    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Evidence
        run: curl -X POST '${{ secrets.evidence_deploy_hook_url }}'

  deploy_docs:
    name: Deploy docs
    # Add a dependency to the build job
    needs: deploy_dbt

    # Deploy to the github-pages environment
    environment:
      name: dbt_docs
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
