name: schedule_dbt_job

on:
  schedule:
    # run at 7AM every single day
    # https://crontab.guru <-- for generating CRON expression
    - cron: "0 7 * * *"
  push:
    branches:
      # run on push to main branch
      - main
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: ".github"
  motherduck_token: ${{ secrets.motherduck_token }}
  DBT_ENV_SECRET_S3_KEY_ID: ${{ secrets.DBT_ENV_SECRET_S3_KEY_ID }}
  DBT_ENV_SECRET_S3_SECRET_KEY: ${{ secrets.DBT_ENV_SECRET_S3_SECRET_KEY }}

jobs:
  schedule_dbt_job:
    name: schedule_dbt_job
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          pip install dbt-duckdb==1.6
          dbt deps
      # dbt related commands here - run use --target prod/dev to run for specific environments
      - name: Run dbt models
        run: dbt build --target prod

      - name: Generate docs
        run: dbt docs generate

      - name: Create GitHub Pages artifact
        run: tar -zcvf github-pages target

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: "target/"
